spring:
  application:
    name: sionoj-backend-judge-service  # 应用名称
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.12:3306/sionoj
    username: root
    password: wick1234
  # Redis 配置
  redis:
    database: 1
    host: 10.211.55.12
    port: 6379
    timeout: 5000

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

  # Nacos 配置
  cloud:
    nacos:
      discovery:
        server-addr: 10.211.55.12:8848  # Nacos 服务器地址和端口
      config:
        server-addr: 10.211.55.12:8848  # 配置中心服务器地址（可选）

server:
  address: 0.0.0.0
  port: 8104
  servlet:
    context-path: /api/user
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 代码沙箱配置
codesandbox:
  type: remote